apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopmate-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopmate-notification
  template:
    metadata:
      labels:
        app: shopmate-notification
    spec:
      containers:
        - name: notification-service
          image: shopmate-notification:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8008
          env:
            - name: PORT
              value: "8008"
---
apiVersion: v1
kind: Service
metadata:
  name: shopmate-notification
spec:
  ports:
    - port: 8008
      targetPort: 8008
  selector:
    app: shopmate-notification
